USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE DT_MEDIUM 
WITH 
	WAREHOUSE_SIZE = 'MEDIUM' 
	WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 600 
	AUTO_RESUME = TRUE 
	MIN_CLUSTER_COUNT = 1 
	MAX_CLUSTER_COUNT = 2 
	SCALING_POLICY = 'STANDARD';
	
ALTER WAREHOUSE "DT_MEDIUM" SUSPEND;
GRANT OWNERSHIP ON WAREHOUSE DT_MEDIUM TO ROLE BI_DBA;