--Permissions to grant permissions on tables, stage, file format to Matillion Application Role user

--On the staging schema
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BISHAL_TEST TO ROLE MATILLION_DEV_DDL COPY CURRENT GRANTS;

--On the target schema
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BISHAL_DM TO ROLE MATILLION_DEV_DDL COPY CURRENT GRANTS;

--On S3 Stagbe in Snowflake
GRANT OWNERSHIP ON STAGE BISHAL_TEST.BISHAL_STAGE TO ROLE MATILLION_DEV_DDL COPY CURRENT GRANTS;

--On S3 FileFormat in Snowflake
GRANT USAGE ON FILE FORMAT BISHAL_TEST.FORMAT_NDJSON TO ROLE MATILLION_DEV_DDL COPY CURRENT GRANTS;

